apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdb
spec:
  replicas: 3
  selector:
    matchLabels:
      appdb: db
  template:
    metadata:
      labels:
        appdb: db
    spec:
      containers:
      - name: ctn-travel-db
        image: postgres:latest
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: dbsvc
spec:
  selector:
    appdb: db
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30000
