apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: ctn-app
        image: 828370275182.dkr.ecr.us-west-2.amazonaws.com/travel:1.0
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: postgres-config
        env:
        - name: spring.profiles.active
          value: postgresql
        - name: POSTGRES_DB
          value: travel
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: admin
        - name: DB_SVC
          value: dbsvc
---
apiVersion: v1
kind: Service
metadata:
  name: websvc
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
    - name: web
      port: 8080
      targetPort: 8080
