apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: ctn-travel-db
        image: postgres:latest
        ports:
        - containersPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: dbsvc
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
